namespace Fint.Sse.Adapter
{
    public enum AdapterArchiveAction
    {
        GET_ALL_DOKUMENTSTATUS,
        GET_ALL_DOKUMENTTYPE,
        GET_DOKUMENTFIL,
        UPDATE_DOKUMENTFIL,
        GET_ALL_JOURNALSTATUS,
        GET_ALL_JOURNALPOSTTYPE,
        GET_KORRESPONDANSEPART,
        UPDATE_KORRESPONDANSEPART,
        GET_ALL_KORRESPONDANSEPARTTYPE,
        GET_ALL_MERKNADSTYPE,
        GET_PART,
        GET_ALL_PARTROLLE,
        GET_SAK,
        GET_ALL_SAKSSTATUS,
        GET_ALL_SKJERMINGSHJEMMEL,
        GET_ALL_TILGANGSRESTRIKSJON,
        GET_ALL_TILKNYTTETREGISTRERINGSOM,
        GET_ALL_VARIANTFORMAT,
        
    }
    
}
